const products=[
    {
        "companyName":'AMZN',
        "productDetails":[
            {
            "type":'TV',
            "price":30000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'Phone',
            "price":25000,
            "availability":true,
            "rating":2.4
        },
        {
            "type":'Moniter',
            "price":24000,
            "availability":true,
            "rating":2.7
        },
        {
            "type":'Keyboard',
            "price":2000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'TV Stick',
            "price":5500,
            "availability":true,
            "rating":3.9
        },
    ],
},
{
        "companyName":"MCRSFT",
        "productDetails":[
            {
            "type":'TV',
            "price":30000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'Phone',
            "price":25000,
            "availability":true,
            "rating":2.4
        },
        {
            "type":'Moniter',
            "price":24000,
            "availability":true,
            "rating":2.7
        },
        {
            "type":'Keyboard',
            "price":2000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'TV Stick',
            "price":5500,
            "availability":true,
            "rating":3.9
        },
    ],
},
{
        "companyName":"APL",
        "productDetails":[
            {
            "type":'TV',
            "price":30000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'Phone',
            "price":25000,
            "availability":true,
            "rating":2.4
        },
        {
            "type":'Moniter',
            "price":24000,
            "availability":true,
            "rating":2.7
        },
        {
            "type":'Keyboard',
            "price":2000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'TV Stick',
            "price":5500,
            "availability":true,
            "rating":3.9
        },
    ],
},
{
        "companyName":"NKIA",
        "productDetails":[
            {
            "type":'TV',
            "price":30000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'Phone',
            "price":25000,
            "availability":true,
            "rating":2.4
        },
        {
            "type":'Moniter',
            "price":24000,
            "availability":true,
            "rating":2.7
        },
        {
            "type":'Keyboard',
            "price":2000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'TV Stick',
            "price":5500,
            "availability":true,
            "rating":3.9
        },
    ],
},
{
        "companyName":"ADBE",
        "productDetails":[
            {
            "type":'TV',
            "price":30000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'Phone',
            "price":25000,
            "availability":true,
            "rating":2.4
        },
        {
            "type":'Moniter',
            "price":24000,
            "availability":true,
            "rating":2.7
        },
        {
            "type":'Keyboard',
            "price":2000,
            "availability":true,
            "rating":3.4
        },
        {
            "type":'TV Stick',
            "price":5500,
            "availability":true,
            "rating":3.9
        },
    ],
    }
]
module.exports=products;